### PR TITLE
Created MapView class and added showMap function

### PR DESCRIPTION
**Pull request by DhananjayNarayan**
Have added the functionality as desired and have tested it. No conflicts whatsover as of now. Created functions to handle and store the names of neighbors of a country. Added some JavaDoc to the same.

### CODE REVIEW

**Comment by madhuhema** [comment]
Checked and ready to get merged

**Review by madhuhema — APPROVED** [review]
Approved !!

**Comment by neonapinto** [comment]
Approved

**Review by PrathikaSuvarna — APPROVED** [review]

**Comment by PrathikaSuvarna** [comment]
Approved

**Pull request merged**
